version: '3.1'

services:
  mysql:
    #platform: linux/arm64
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
      - "./docker/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql"
  nginx:
    image: nginx
    restart: unless-stopped
    command: [nginx-debug, '-g', 'daemon off;']
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    volumes:
      - "./www:/usr/share/nginx/html"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
