// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func TopNavigation(cmp Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar navbar-expand-lg bg-body-primary mb-3 mt-1\"><div class=\"container-fluid\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmp.User() != nil {
			templ_7745c5c3_Err = ProfileNavButton(cmp).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#top-nav\" aria-controls=\"top-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button><div id=\"top-nav\" class=\"collapse navbar-collapse justify-content-left\" hx-swap-oob=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(TrueFalse(cmp.IsOOB())))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmp.User() != nil {
			templ_7745c5c3_Err = UserNavigation(cmp).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = GuestNavigation().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func GuestNavigation() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<ul hx-target=\"#content-root\" hx-push-url=\"true\" class=\"navbar-nav guest-nav mb-2 mt-2 mb-lg-0\"><li class=\"nav-item m-auto\"><a class=\"nav-link\" title=\"Home\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\" hx-get=\"/\"><img src=\"/static/prmry.png\" class=\"navbar-img\"></a></li><li class=\"nav-item m-auto\"><a class=\"nav-link\" title=\"Terms of Service\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\" hx-get=\"/legal/terms\">TOS</a></li><li class=\"divider d-none d-md-block pt-1  m-auto\">&nbsp;|&nbsp</li><li class=\"nav-item  m-auto\"><a class=\"nav-link\" title=\"Privacy Policy\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\" hx-get=\"/legal/privacy\">Privacy</a></li><li class=\"divider d-none d-md-block pt-1 m-auto\">&nbsp;|&nbsp</li><li class=\"nav-item m-auto\"><a class=\"nav-link\" title=\"Source Code\" target=\"_blank\" href=\"https://github.com/itsnoproblem/prmry\">Source Code</a></li></ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func ProfileNavButton(cmp Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><img class=\"img-fluid navbar-avatar\" alt=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(cmp.User().Name))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(cmp.User().AvatarURL))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></a><ul class=\"dropdown-menu\" hx-target=\"#content-root\" hx-push-url=\"true\"><li><a class=\"dropdown-item\" hx-get=\"/account\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\">Profile</a></li><li><hr class=\"dropdown-divider\"></li><li><a class=\"dropdown-item\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 templ.SafeURL = templ.SafeURL("/auth/logout/" + cmp.User().Provider)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var4)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">Log out</a></li><li><hr class=\"dropdown-divider\"></li><li><a class=\"dropdown-item\" title=\"Terms of Service\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\" hx-get=\"/legal/terms\">TOS</a></li><li><a class=\"dropdown-item\" title=\"Privacy Policy\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\" hx-get=\"/legal/privacy\">Privacy</a></li></ul></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func UserNavigation(cmp Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<ul class=\"navbar-nav me-auto mb-2 mt-2 mb-lg-0 text-end\"><li class=\"nav-item text-lg-center ms-4\"><a class=\"nav-link d-block text-lg-center\" title=\"Flows\" hx-get=\"/flows\" hx-target=\"#content-root\" hx-push-url=\"true\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\"><span class=\"d-lg-none smaller pe-3\">flows</span> <i class=\"fa fa-water fa-2x pb-2\"></i><div class=\"d-none d-lg-block smaller\">flows</div></a></li><li class=\"nav-item text-lg-center ms-4\"><a class=\"nav-link d-block text-lg-center\" title=\"Funnels\" hx-get=\"/funnels\" hx-target=\"#content-root\" hx-push-url=\"true\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\"><span class=\"d-lg-none smaller pe-3\">funnels</span> <i class=\"fa fa-filter fa-2x pb-2\" aria-hidden=\"true\"></i><div class=\"d-none d-lg-block smaller\">funnels</div></a></li><li class=\"nav-item text-lg-center ms-4\"><a class=\"nav-link d-block text-lg-center\" title=\"Generate\" hx-get=\"/interactions/chat\" hx-target=\"#content-root\" hx-push-url=\"true\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\"><span class=\"d-lg-none smaller pe-3\">generate</span> <i class=\"fa fa-bolt fa-2x pb-2\" aria-hidden=\"true\"></i><div class=\"d-none d-lg-block smaller\">generate</div></a></li><li class=\"nav-item text-lg-center ms-4\"><a class=\"nav-link d-block text-lg-center\" title=\"History\" hx-get=\"/interactions\" hx-target=\"#content-root\" hx-push-url=\"true\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse.show\"><span class=\"d-lg-none smaller pe-3\">history</span> <i class=\"fa-solid fa-clock-rotate-left  fa-2x pb-2\"></i><div class=\"d-none d-lg-block smaller\">history</div></a></li></ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
